name: esp32 port

on:
  push:
  pull_request:
    paths:
      - '.'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_idf44:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: source tools/ci.sh && ci_esp32_idf44_setup
    - name: Build
      run: source tools/ci.sh && ci_esp32_build
